Repository TECHOUS/AlgoHeist, pull requests merged in 2020-10, with the labels that each got.

#92 Updated binarySearch.py
  SEARCHING/BINARY-SEARCH/Python/binarySearch.py
Labels: HacktoberFest20

#90 topological Sort
  GRAPH_ALGORITHMS/topologicalSort.cpp
  README.md
Labels: C++, HacktoberFest20

#107 added Binary Search with recursion in JavaScript.
  README.md
  SEARCHING/BINARY-SEARCH/JAVASCRIPT/BinarySearchWithRecursion.js
Labels: HacktoberFest20, JS

#106 added Quick Sort in JavaScript.
  README.md
  SORTING/QUICK-SORT/JAVASCRIPT/QuickSort.js
Labels: HacktoberFest20, JS

#95 added Bubble Sort in Golang
  README.md
  SORTING/BUBBLE-SORT/Go/BubbleSort.go
Labels: GO, HacktoberFest20

#115 Update README.md
  README.md
Labels: good first issue

#114 key to character mapping
  README.md
  STRINGS/printKPC/PYTHON/getKPC.ipynb
Labels: HacktoberFest20, Python

#124 created coin change permutation
  MISC/Coin_Change_Permutation/PYTHON/CoinChangePer.py
  README.md
Labels: HacktoberFest20, Python

#104 subsequence of a sequence
  README.md
  STRINGS/Subsequence/PYTHON/Subsequence.ipynb
Labels: HacktoberFest20, Python

#108 Create sparse_matrix_addition.c
  MISC/sparse_matrix.c
  README.md
Labels: C, HacktoberFest20

#112 ADDED EQUILLIBRIUM POINT AND SUBARRAY WITH GIVEN SUM
  MISC/equillibrium_point_in_array./c++.cpp
  MISC/kandane algo/c++.cpp
  MISC/subarray_with_given_sum/c++.cpp
  README.md
Labels: C++

#125 created maximum non adjacent sum (dynamic programming)
  MISC/Max_Sum/PYTHON/MaxNonAdjacentSum.py
  README.md
Labels: HacktoberFest20, Python

#122 Half_Reverse_Pyramid
  MISC/HALF_reverse_PYRAMID.py
  README.md
Labels: HacktoberFest20, Python

#120 Pattern_rhombus_by-python
  MISC/rhombus_patt.py
  README.md
Labels: HacktoberFest20, Python

#135 added Golang in selection sort section and updated README.
  README.md
  SORTING/SELECTION-SORT/Go/SelectionSort.go
Labels: GO, HacktoberFest20

#128 Fibonacci_XOR problem added
  MISC/Fibonacci_xor/C++/fibonacci_xor.cpp
  README.md
Labels: C++, HacktoberFest20

#131 Added program to calculate Prime Factorization of a number
  MISC/Kadane_Algorithm/C++/kadane.cpp
  MISC/prime_factorization/prime_factorization.cpp
  README.md
Labels: C++, HacktoberFest20, hacktoberfest-accepted

#150 Added an animated quick sorting algorithm in Python.
  README.md
  SORTING/QUICK-SORT/Python/animated_quick_sort.py
Labels: HacktoberFest20, Python, hacktoberfest-accepted

#145 Create FactorialUsingRecursion.java
  MISC/FactorialUsingRecursion.java
  README.md
Labels: HacktoberFest20, JAVA, hacktoberfest-accepted
