Repository TECHOUS/AlgoHeist, pull requests merged in 2021-10, with the labels that each got.

#163 AlgoHeist21: Palindrome and Anagram
  strings/anagram/anagram.js
  strings/pallindrome/palindrome.js
Labels: JavaScript, hacktoberfest-accepted, HacktoberFest21

#164 AlgoHeist21: Quick Sort Algorithm in JAVA
  sorting/quick_sort/quickSort.java
Labels: Java, hacktoberfest-accepted, HacktoberFest21

#166 AlgoHeist21: Kadane's algorithm
  README.md
  misc/kadane_algorithm/kadane.py
Labels: Python, hacktoberfest-accepted, HacktoberFest21

#165 AlgoHeist21: Bellman-Ford Algorithm
  README.md
  graphs/bellman_ford/bellmanFord.cpp
Labels: C++, hacktoberfest-accepted, HacktoberFest21

#172 AlgoHeist21: Fix many typos
  README.md
  graphs/kruskal/kruskal.cpp
  misc/equilibrium_point_of_an_array/equilibriumPoint.cpp
  strings/palindrome/palindrome.c
  strings/palindrome/palindrome.cpp
  strings/palindrome/palindrome.java
  strings/palindrome/palindrome.js
  strings/palindrome/palindrome.py
Labels: good first issue, hacktoberfest-accepted, HacktoberFest21

#169 AlgoHeist21: Iterative Linear Search
  README.md
  searching/linear_search/linearSearchIteratively.rb
Labels: hacktoberfest-accepted, HacktoberFest21, Ruby

#167 AlgoHeist21: Sieve of Eratosthenes in Python
  misc/sieve_of_eratosthenes/SieveOfEratosthenes.py
Labels: Python, hacktoberfest-accepted, HacktoberFest21

#177 AlgoHeist21: Segmented Sieve
  misc/segmented_sieve/segmentedSieve.py
Labels: Python, hacktoberfest-accepted, HacktoberFest21

#176 AlgoHeist21: String Reversal
  README.md
  strings/reverse_a_string/reverseString.rb
Labels: hacktoberfest-accepted, HacktoberFest21, Ruby

#182 AlgoHeist21: caesarCipher.cpp
  README.md
  misc/caesar_cipher/caesarCipher.cpp
Labels: C++, hacktoberfest-accepted, HacktoberFest21

#184 AlgoHeist21: Ternary search
  README.md
  searching/ternary_search/ternarySearch.cpp
Labels: C++, HacktoberFest21

#186 AlgoHeist21: Bucket Sort w/signoff
  README.md
  sorting/bucket_sort/bucketSort.cpp
Labels: C++, hacktoberfest-accepted, HacktoberFest21

#171 AlgoHeist21: Linear Search
  README.md
  searching/linear_search/linearSearch.py
Labels: Python, hacktoberfest-accepted, HacktoberFest21

#189 AlgoHeist21: Strongly Connected Components
  README.md
  graphs/strongly_connected_components/scc.cpp
Labels: C++, hacktoberfest-accepted, HacktoberFest21
